---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - APP_KEY=base64:rNzfycOuamwEZi6vfK7iRr2Yws3mSFdcS0M9zDYdDg4=
      - APP_URL=localhost:80
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=
      - SPEEDTEST_SERVERS=
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=America/Chicago #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
      - SPEEDTEST_SCHEDULE="30 * * * *"
      - SPEEDTEST_SERVER=63775
    volumes:
      - ./config:/config
    ports:
      - 80:80
    restart: unless-stopped

